parser: '@typescript-eslint/parser'
env:
  es2022: true
  node: true
extends:
  - metarhia
  - plugin:sonarjs/recommended
  - prettier
plugins:
  - sonarjs
  - '@typescript-eslint'
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 'off'
